package se.enumDefine.reason;

public enum Reason {
	/**
	 * 注册登录失败原因
	 */
	USERNAME_IS_NULL,
	USERNAME_NOT_EXIST,
	USERNAME_EXIST,
	USERNAME_TOO_SHORT,
	USERNAME_TOO_LONG,
	USERNAME_ILLEAGAL_CHARACTER,
	PASSWORD_IS_NULL,
	PASSWORD_INCORRECT,
	PASSWORD_TOO_SHORT,
	PASSWORD_TOO_LONG,
	PASSWORD_ILLEAGAL_CHARACTER,
	NICKNAME_IS_NULL,
	NICKNAME_TOO_SHORT,
	NICKNAME_TOO_LONG,
	EMAIL_IS_NULL,
	EMAIL_ILLEGAL,
	EMAIL_TOO_LONG,
	PHONE_NUMBER_TOO_LONG,
	PHONE_NUMBER_ILLEGAL,
	ADDERSS_TOO_LONG,
	
	
	/**
	 * 货品模块失败原因
	 */
	GOOD_EXIST,
}
